<a href="https://colab.research.google.com/github/virbickt/aers/blob/master/Untitled7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns;sns.set()

In [3]:
county_facts = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vQBakCivIwMI6g1wLMHwvODKVSpY70D-dbeaQanh1i1vl1kMeBvpMApXazTXXa1vPXignSEOAxkGFxM/pub?output=csv')
county_facts_dict = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vSOWGLhyGIf0wGoamZgD91HjkIXoKTjljTesoyPJ_P18y_fnZ66bm24eKw5xM89r1dteTHG8Gpq39zW/pub?output=csv")
primary_results = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vTyChEtaOCByzFOBSJSWwSfueA3O5umHQmEpc79qryDn5nnDD5e-ZDM-TmfVPAKLsdEDVn-JHlaTw9a/pub?output=csv')

In [19]:
state_facts = county_facts[county_facts.isna().any(axis=1)].drop(0).reset_index().drop(columns=['index', 'fips', 'state_abbreviation'])

In [20]:
state_facts.head()

    area_name  PST045214  PST040210  ...  BPS030214  LND110210  POP060210
0     Alabama    4849377    4780127  ...      13369   50645.33       94.4
1      Alaska     736732     710249  ...       1518  570640.95        1.2
2     Arizona    6731484    6392310  ...      26997  113594.08       56.3
3    Arkansas    2966369    2915958  ...       7666   52035.48       56.0
4  California   38802500   37254503  ...      83645  155779.22      239.1

[5 rows x 52 columns]

In [5]:
swing_states = ['Colorado', 'Florida', 'Iowa', 'Michigan', 'Nevada', 'New Hampshire', 'North Carolina', 'Ohio', 'Pennsylvania', 'Virginia', 'Winconsin']

In [28]:
swing_state_facts = state_facts.loc[state_facts['area_name'].isin(swing_states)].reset_index().drop(columns=['index'])

In [30]:
swing_state_facts.head()

  area_name  PST045214  PST040210  ...  BPS030214  LND110210  POP060210
0  Colorado    5355866    5029324  ...      28686  103641.89       48.5
1   Florida   19893297   18804623  ...      84075   53624.76      350.6
2      Iowa    3107126    3046869  ...      10256   55857.13       54.5
3  Michigan    9909877    9884133  ...      15933   56538.90      174.8
4    Nevada    2839099    2700692  ...      13016  109781.18       24.6

[5 rows x 52 columns]

In [33]:
swing_state_ed_facts = swing_state_facts[['area_name', 'PST045214', 'EDU635213', 'EDU685213']].copy().rename(columns={"A": "a", "B": "c"})

In [35]:
swing_state_ed_facts

        area_name  PST045214  EDU635213  EDU685213
0        Colorado    5355866       90.2       37.0
1         Florida   19893297       86.1       26.4
2            Iowa    3107126       91.0       25.7
3        Michigan    9909877       88.9       25.9
4          Nevada    2839099       84.6       22.4
5   New Hampshire    1326813       91.8       33.7
6  North Carolina    9943964       84.9       27.3
7            Ohio   11594163       88.5       25.2
8    Pennsylvania   12787209       88.7       27.5
9        Virginia    8326289       87.5       35.2

In [ ]:
swing_state_ed_facts['high_school_numbers'] = swing_state_ed_facts['EDU635213'].